define([
    'jquery',
    'mage/utils/wrapper'
], function ($, wrapper) {
    'use strict';

    return function (targetModule) {
        return wrapper.wrap(targetModule, function (originalModule) {
            var module = originalModule;

            // Modify validation for email field 
            var validate = module.validate;
            module.validate = wrapper.wrap(validate, function (originalMethod) {
                var element = this.element;
                
                // Skip validation for email if it's generated by the system
                if (element && element.name === 'email' && $('[data-role="phonemail-config"]').data('phonemail-enabled') === '1') {
                    return true;
                }
                
                return originalMethod();
            });

            return module;
        });
    };
});